- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-server/src/main/java/com/gbsb/routie_server/controller/ItemController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/UserController.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RewardRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserService.java
회원가입할 때 해당 사용자 id로 리워드 테이블이 생성되도록 기능 추가
초기 골드와 걸음 수는 모두 0으로 설정
사용자 이름, 비밀번호 수정하는 기능 추가
사용자 삭제 기능 추가
> 회원가입 후 보상 데이터 생성

- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineController.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/User.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineService.java
routine 테이블에서 userId 참조하도록 설정했으니 포스트맨 실행 시, 테이블 드롭하고 테스트 하는 것을 추천
User 클래스는 getter setter 어노테이션 한 줄에 나열함 별다른 기능 수정 없음
> 운동 루틴 생성, 목록 조회, 수정, 삭제 기능 추가

- routie-mobile/app/build.gradle.kts
- routie-server/src/main/java/com/gbsb/routie_server/controller/UserController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/LoginRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/LoginResponseDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/SignupRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/UserDto.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/UserRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserService.java
일단 서버쪽 코드만 수정했어요
로그인, 회원가입, 유저정보
> 유저 정보 dto 추가

- routie-mobile/app/build.gradle.kts
- routie-server/src/main/java/com/gbsb/routie_server/controller/AdminController.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/UserRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/AdminService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserService.java
AdminController
AdminService
사용자 이메일 조회 -> 사용자 id 조회로 수정
UserService 
중복 이메일 확인 추가
사용자 정보가 null값이 아닐 때만 수정되도록 함
UserRepository
중복 이메일 체크를 위해 이메일 조회 추가
> 사용자 id 조회, 이메일 조회 추가 수정

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/TestActivity.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RewardApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RewardResponse.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/viewmodel/RewardViewModel.kt
- routie-mobile/app/src/main/res/layout/activity_test.xml
api 변경에 맞춰 연결 코드 수정
불필요한 retrofit 인스턴스 삭제
Toast메시지 문구 변경
userId int->String
결과적으로 userId 입력 시, gold, steps 불러옴
칼로리 전송 시, gold가 늘어나고 서버에 저장됨
> test 화면에서 리워드 조회, 지급 기존 api 연결 수정

- routie-server/src/main/java/com/gbsb/routie_server/controller/ExerciseCategoryController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/ExerciseController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineExerciseController.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Exercise.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/ExerciseCategory.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/RoutineExercise.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/ExerciseCategoryRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/ExerciseRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineExerciseRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/ExerciseCategoryService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/ExerciseService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineExerciseService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineService.java
운동, 운동 카테고리 엔티티 추가
루틴 생성 기능은 말로 설명하기 복잡해서 노션 - 백엔드 - database에 postman테스트 결과 올려놨어요
확인 후 수락해주세요.
만약 테스트 할거면 운동 카테고리 등록과 운동 등록은 워크벤치에서 하셔야 합니다.
> 루틴에 운동 추가, 수정, 삭제 기능 구현

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/SettingActivity.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/StoreFragment.kt
- routie-mobile/app/src/main/res/layout/activity_setting.xml
로그아웃 버튼 클릭시 로그인 창으로 이동
스토어 버튼 이벤트 추가중
> 설정창 이벤트 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/MainActivity.kt
- routie-mobile/app/src/main/res/layout/activity_main.xml
*앱 실행 안되는 오류 해결
**반드시!!!!! 컴퓨터에서 그레이들 업데이트 해주세요! 3.6.0이상**
***그레이들 버전 변경하지 말아주세요. 최적화해놓은거임!!***
> 앱 실행 안되는 오류 해결

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/LoginFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/SignupFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/navigation/nav_graph.xml
- routie-mobile/gradle.properties
- routie-mobile/gradle/wrapper/gradle-wrapper.properties
걍 로그인없이 메인화면으로 이동
필요없는 import 삭제
그레이들 설치 문제 있으신 분들을 위해 gradlew 파일까지 커밋합니다~
> 로그인화면 -> 회원가입버튼 -> 완료버튼 -> 메인화면 순으로 이동

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/AccountFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/AlarmFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/LoginFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/SettingFragment.kt
- routie-mobile/app/src/main/res/layout/fragment_account.xml
- routie-mobile/app/src/main/res/layout/fragment_alarm.xml
- routie-mobile/app/src/main/res/layout/fragment_setting.xml
- routie-mobile/app/src/main/res/navigation/nav_graph.xml
SettingFragment의 버튼 이동 액션 추가 했습니다.
MainFragment의 네비게이션 충돌 위혐 코드 제거.
> SettingFragment Button Event, Modify code for crack

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MakingroutineFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_makingroutine.xml
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/RoutineExercise.java
사용자 id로 루틴을 생성하고 저장하는 기능 추가
caloriesBurned, duration 일단 임의 값으로 넣어 둠
> 루틴 생성 저장 기능 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/ExerciseRequest.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RoutineRequest.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MakingroutineFragment.kt
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineExerciseController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/ExerciseRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/RoutineExercise.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineExerciseService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineService.java
routine_exercise 테이블은 칼로리와 시간이 업데이트 되는데, routine 테이블에선 총 칼로리와 총 운동시간이 0으로 표시됨.
실행 안 되는 코드, 아직 안 쓰는 코드 주석처리 해놓음.
> 운동 소모 칼로리 계산 기능 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/UserApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/PasswordUpdateRequest.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/UserUpdateRequest.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/LoginFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/UserInfoFragment.kt
- routie-mobile/app/src/main/res/navigation/nav_graph.xml
- routie-server/src/main/java/com/gbsb/routie_server/controller/UserController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/PasswordUpdateRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/UpdateUserRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserService.java
회원 정보 변경 
- 키, 몸무게, 이메일 변경 가능
- 비밀번호는 기존 비밀번호 확인 후 변경
회원탈퇴
- user와 외래키로 엮인 테이블 삭제 후 탈퇴되게 api 수정
- 탈퇴 후 로그인창으로 이동
> 회원정보 변경, 탈퇴 완료

- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineRepository.java
> 회원정보 변경, 탈퇴 완료2

- routie-mobile/app/build.gradle.kts
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/adapter/WeekDayAdapter.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/WeekDay.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/res/layout/fragment_main.xml
- routie-mobile/app/src/main/res/layout/item_week_day.xml
localDate 받아서 해당 주간 날짜 띄움
날짜 디자인은 item_week_Day.xml 파일에 임시로 만들어 놓음
추후에 디자인 변경 필요
> 캘린더에 해당 주 날짜 띄우기

- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineLogController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineLogDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/ExerciseLog.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/RoutineLog.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineLogRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineLogService.java
루틴 로그 조회 추가
해당 날짜의 모든 루틴 기록 가져오기 위해 루틴로그 레포지토리에 sql 쿼리 추가
> 루틴 로그 조회 시 총 칼로리, 운동 시간 응답 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/adapter/RoutineLogAdapter.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineLogApi.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/ExerciseLog.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RoutineLog.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_main.xml
- routie-mobile/app/src/main/res/layout/item_routine_log.xml
exercise log 테이블에 있는 정보를 스케치북에 띄움
> 날짜 선택 시 해당 날짜의 운동 데이터 불러오기

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/adapter/ExerciseResponseAdapter.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/ModifyroutineFragment.kt
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineExerciseController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/ExerciseResponseDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/ExerciseLog.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineExerciseService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineService.java
루틴 생성 시, 사용자가 날짜를 선택 안 하면 당일 날짜로 들어감
추후에 캘린더와 연결할 예정
exerciseLog 엔티티에서 caloriesBurned, duration 값은 초기 기본값 0으로 생성되게 변경
> 루틴 api에 날짜 설정 추가

- routie-mobile/app/src/main/res/layout/fragment_makingroutine.xml
> 생성 버튼 깨짐 재배치(수정)(최종)

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RoutineResponse.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RoutineUpdateRequest.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/ModifyroutineFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_makingroutine.xml
- routie-mobile/app/src/main/res/layout/fragment_modifyroutine.xml
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineUpdateRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Routine.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineService.java
루틴 수정 시, 요일까지 수정되게 api 변경
필요없는 주석 삭제
안드로이드 ModifyroutineFragment에 요일 선택 추가
선택된 요일로 변경 되게 api 연결 완료
> 루틴 요일 수정 추가

- routie-server/src/main/java/com/gbsb/routie_server/controller/ExerciseLogController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineDayController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineDayDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/WorkoutRecordDto.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/ExerciseLogRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineDayRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/ExerciseLogService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineDayService.java
- 서버 -> 클라이언트 :
해당 요일의 루틴, 운동 Id
- 클라이언트 -> 서버 :
워치 환경에서 측정된 데이터(dto) 값을 넘겨줌. routineId, exercsieId, duration 서버 : 받은 값을 caloriesPerSencond를 참조하여 caloriesBurned = caloriesperSecond * duration 값으로 넣어줌(변수명 틀리면 ㅈㅅ) 
**_추가적으로 ExerciseLog 엔티티를 새로 만들어서 운동별로 로그가 저장되도록 했습니다.이 부분 확인 부탁드려요!_**
> 워치 데이터를 위한 서버 환경 구축

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/SettingFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_setting.xml
- routie-server/src/main/java/com/gbsb/routie_server/controller/UserController.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserService.java
사용자 정보 조회 api 추가함
프로필 밑에 설정된 닉네임 불러와서 표시함
> 설정 화면에 닉네임 불러오기 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/StoreFragment.kt
- routie-mobile/app/src/main/res/drawable/bg_category_button.xml
- routie-mobile/routie-wear/src/main/java/com/example/routie_wear/ui/RoutineListScreen.kt
- routie-mobile/routie-wear/src/main/java/com/example/routie_wear/ui/StartScreen.kt
- routie-mobile/routie-wear/src/main/java/com/example/routie_wear/ui/theme/Theme.kt
(완료)스타트 화면, 루틴리스트화면 폰트 사이즈 및 색상 개선
> 워치 화면 수정사항

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/CharacterApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/CharacterStyleResponseDto.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MyroomFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/StoreFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_main.xml
- routie-mobile/app/src/main/res/layout/fragment_myroom.xml
- routie-mobile/app/src/main/res/layout/fragment_store.xml
메인화면에 캐릭터 스타일 조회하는 api 연결하는 김에 
마이룸, 상점에 있는 캐릭터들까지 동일한 방식으로 연결함
> 캐릭터 스타일 api 연결

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RoutineApiService.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RoutineDayResponse.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MainFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_main.xml
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineDayController.java
- routie-server/src/main/java/com/gbsb/routie_server/controller/RoutineLogController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/RoutineDayDto.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/RoutineDayRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineDayService.java
- routie-server/src/main/java/com/gbsb/routie_server/service/RoutineLogService.java
수정 사항
루틴이 요일에 맞게 반복 조회
루틴 생성 날짜를 기준으로 과거 날짜에는 새로운 루틴 표시X
말풍선에 총 소모 칼로리, 운동 시간 표시됨
> 루틴 조회 요일 기반으로 수정

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/SettingFragment.kt
- routie-server/src/main/java/com/gbsb/routie_server/controller/AchievementController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/AchievementDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/Achievement.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/UserAchievement.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/AchievementRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/UserAchievementRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/AchievementService.java
설정 화면에 프로필 업로드 부분 수정
업적 조회 및 생성 api 추가
> 설정 화면 기능 수정 및 업적 api 추가

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/RankingApi.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/config/ServerConfig.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/LoginResponse.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RankingItem.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/RankingResponse.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/User.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/LoginFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/RankingFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/SettingFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-server/src/main/java/com/gbsb/routie_server/controller/UserController.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/LoginResponseDto.java
로그인 시, 프로필 사진 url 응답 추가
랭킹 기준은 칼로리 소모량으로 일단 해 놓음
프로필 사진 동그랗게 띄우기 성공!!
> 랭킹 10위까지 표시

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/api/TicketApi.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/config/ServerConfig.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/GachaResultDto.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/TicketCountDto.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/dto/TicketUseRequestDto.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/GachaDialogFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/MyroomFragment.kt
- routie-mobile/app/src/main/java/com/gbsb/routiemobile/network/RetrofitClient.kt
- routie-mobile/app/src/main/res/layout/fragment_myroom.xml
- routie-mobile/app/src/main/res/layout/gacha_dialog.xml
- routie-mobile/routie-wear/src/main/java/com/example/routie_wear/network/RetrofitInstance.kt
- routie-mobile/routie-wear/src/main/res/xml/network_security_config.xml
- routie-server/src/main/java/com/gbsb/routie_server/dto/GachaResultDto.java
- routie-server/src/main/java/com/gbsb/routie_server/dto/TicketRequestDto.java
- routie-server/src/main/java/com/gbsb/routie_server/entity/GachaLog.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/GachaLogRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserItemService.java
그 외 엔티티 부분 추가(레어 아이템, 가챠 실패 엔티티)
> 가챠 티켓 수 증가/증감 코드 적용

- routie-mobile/app/src/main/java/com/gbsb/routiemobile/fragment/GachaDialogFragment.kt
- routie-server/src/main/java/com/gbsb/routie_server/dto/GachaResultDto.java
- routie-server/src/main/java/com/gbsb/routie_server/repository/GachaLogRepository.java
- routie-server/src/main/java/com/gbsb/routie_server/service/UserItemService.java
엔티티값과 연결이 안되는 문제 해결( @JsonProperty("isHiddenItem")) 사용
코드는 문제 없었음. 서버 측에서 연결이 잘 안됨. => 해결
> 가챠 테이블 전송값 강력히 맵핑
